version: "3.9"
services:
  person_service:
    image: udaconnect-api
    build:
      context: modules/api
    command: ["poetry" , "run", "uvicorn", "person_api:uda_app", "--host", "0.0.0.0", "--reload", "--port", "5000"]
    ports:
      - "30001:5000"
    environment:
      MONGO_CONNECTION_URI: mongodb://udaconnect_root:tinydogonaleash@localhost:27017/?authMechanism=DEFAULT
      MONGO_DB_NAME: geoconnections
  location_service:
    image: udaconnect-api
    build:
      context: modules/api
    command: ["poetry" , "run", "uvicorn", "location_api:uda_app", "--host", "0.0.0.0", "--reload", "--port", "5000"]
    ports:
      - "30002:5000"
    environment:
      MONGO_CONNECTION_URI: mongodb://udaconnect_root:tinydogonaleash@localhost:27017/?authMechanism=DEFAULT
      MONGO_DB_NAME: geoconnections
  connection_service:
    image: udaconnect-api
    build:
      context: modules/api
    command: ["poetry" , "run", "uvicorn", "connection_api:uda_app", "--host", "0.0.0.0", "--reload", "--port", "5000"]
    ports:
      - "30003:5000"
    environment:
      MONGO_CONNECTION_URI: mongodb://udaconnect_root:tinydogonaleash@localhost:27017/?authMechanism=DEFAULT
      MONGO_DB_NAME: geoconnections
  frontend:
    image: udaconnect-app
    build:
      context: modules/frontend
    environment:
      REACT_APP_API_BASE_URL: http://localhost:30001
    ports:
      - "30000:3000"
  mongodb_udaconnect:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: udaconnect_root
      MONGO_INITDB_ROOT_PASSWORD: tinydogonaleash
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_udaconnect:/data/db

volumes:
  mongodb_data_udaconnect: