version: "3.9"
services:
  api:
    image: udaconnect-api
    build:
      context: modules/api
    ports:
      - "30001:5000"
  frontend:
    image: udaconnect-app
    build:
      context: modules/frontend
    environment:
      REACT_APP_API_BASE_URL: http://localhost:30001
    ports:
      - "30000:3000"
  mongodb_udaconnect:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: udaconnect_root
      MONGO_INITDB_ROOT_PASSWORD: tinydogonaleash
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_udaconnect:/data/db

volumes:
  mongodb_data_udaconnect: