# configuration to use NodePort with Kind.
# Taken from here: https://stackoverflow.com/questions/62432961/how-to-use-nodeport-with-kind

# Every port that should be exposed to host machine needs to be listed below.

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  # UdaConnect:
  extraPortMappings:
  ## Frontend:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0"
    protocol: tcp
  ## PersonService
  - containerPort: 30001
    hostPort: 30001
    listenAddress: "0.0.0.0"
    protocol: tcp
  ## LocationService:
  - containerPort: 30002
    hostPort: 30002
    listenAddress: "0.0.0.0"
    protocol: tcp
  ## ConnectionService:
  - containerPort: 30003
    hostPort: 30003
    listenAddress: "0.0.0.0"
    protocol: tcp
  ## ConnectionTracker:
  - containerPort: 30004
    hostPort: 30004
    listenAddress: "0.0.0.0"
    protocol: tcp
  ## Database:
  - containerPort: 30010
    hostPort: 30010
    listenAddress: "0.0.0.0"
    protocol: tcp
  ## Kafka:
  - containerPort: 30020
    hostPort: 30020
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker