apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection-api
  name: connection-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: connection-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection-api
  name: connection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection-api
  template:
    metadata:
      labels:
        service: connection-api
    spec:
      containers:
      # Remark: This repository does not exist online, but the
      # docker compose builds images tagged with it locally.
      # This is to make it absolutely clear I am using my own
      # docker images and not the pre-built ones.
      - image: local.docker.repo/radimcajzl/connection-api:latest
        name: connection-api
        imagePullPolicy: Always
        env:
        - name: MONGO_CONNECTION_URI
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MONGO_CONNECTION_URI
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: MONGO_DB_NAME
        - name: CONNECTION_TRACKER_HOST
          value: "connection-tracker"
        - name: CONNECTION_TRACKER_PORT
          value: "3004"
        - name: KAFKA_SERVER
          value: "kafka:9092"
      restartPolicy: Always
