apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-processor
  name: location-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-processor
  template:
    metadata:
      labels:
        service: location-processor
    spec:
      containers:
      - image: docker.io/library/udaconnect-api:latest
        name: location-processor
        imagePullPolicy: Always
        command:
        - "poetry"
        - "run"
        - "python"
        - "location_processor.py"
        env:
        - name: MONGO_CONNECTION_URI
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MONGO_CONNECTION_URI
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: MONGO_DB_NAME
        - name: CONNECTION_TRACKER_HOST
          value: "connection-tracker"
        - name: CONNECTION_TRACKER_PORT
          value: "3004"
        - name: KAFKA_SERVER
          value: "kafka:9092"
      restartPolicy: Always
