apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-api
  name: location-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: location-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-api
  name: location-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-api
  template:
    metadata:
      labels:
        service: location-api
    spec:
      containers:
      - image: udacity/nd064-location-api:latest
        name: location-api
        imagePullPolicy: Always
        env:
        - name: MONGO_CONNECTION_URI
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MONGO_CONNECTION_URI
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: MONGO_DB_NAME
      restartPolicy: Always
