apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-api
  name: person-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: person-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-api
  name: person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-api
  template:
    metadata:
      labels:
        service: person-api
    spec:
      containers:
      - image: radimcajzl/udaconnect-person-api:latest
        name: person-api
        imagePullPolicy: Always
        env:
        - name: MONGO_CONNECTION_URI
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MONGO_CONNECTION_URI
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: MONGO_DB_NAME
        - name: CONNECTION_TRACKER_HOST
          value: "connection-tracker"
        - name: CONNECTION_TRACKER_PORT
          value: "3004"
        - name: KAFKA_SERVER
          value: "kafka:9092"
      restartPolicy: Always
