# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection_tracker_api/connection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'connection_tracker_api/connection.proto\"Q\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"U\n\x08Location\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x63oordinates\x18\x03 \x03(\x02\x12\x15\n\rcreation_time\x18\x04 \x01(\t\"B\n\nConnection\x12\x1b\n\x08location\x18\x01 \x01(\x0b\x32\t.Location\x12\x17\n\x06person\x18\x02 \x01(\x0b\x32\x07.Person\"f\n\x11\x43onnectionRequest\x12\x1b\n\x08location\x18\x01 \x01(\x0b\x32\t.Location\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\x0e\n\x06meters\x18\x04 \x01(\x05\x32=\n\x11\x43onnectionTracker\x12(\n\x03Get\x12\x12.ConnectionRequest\x1a\x0b.Connection0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_tracker_api.connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=43
  _PERSON._serialized_end=124
  _LOCATION._serialized_start=126
  _LOCATION._serialized_end=211
  _CONNECTION._serialized_start=213
  _CONNECTION._serialized_end=279
  _CONNECTIONREQUEST._serialized_start=281
  _CONNECTIONREQUEST._serialized_end=383
  _CONNECTIONTRACKER._serialized_start=385
  _CONNECTIONTRACKER._serialized_end=446
# @@protoc_insertion_point(module_scope)
