openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /persons/{person_id}/connection:
    servers:
     - url: http://localhost:30003/
    get:
      summary: Find Contacts For Person
      operationId: find_contacts_for_person_persons__person_id__connection_get
      parameters:
        - required: true
          schema:
            title: Person Id
            type: integer
          name: person_id
          in: path
        - required: true
          schema:
            title: Start Date
            type: string
            format: date
          name: start_date
          in: query
        - required: true
          schema:
            title: End Date
            type: string
            format: date
          name: end_date
          in: query
        - required: false
          schema:
            title: Distance
            type: integer
            default: 5
          name: distance
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: >-
                  Response Find Contacts For Person Persons  Person Id 
                  Connection Get
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /metrics:
    servers:
     - url: http://localhost:30003/
    get:
      summary: Metrics
      description: Returns statistics with recent connections.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiMetrics'
components:
  schemas:
    ApiMetrics:
      title: ApiMetrics
      required:
        - status
        - connection_count_intervals
      type: object
      properties:
        status:
          title: Status
          enum:
            - healthy
          type: string
        connection_count_intervals:
          title: Connection Count Intervals
          type: object
          properties:
            current:
              $ref: '#/components/schemas/ConnectionCountInterval'
            previous:
              $ref: '#/components/schemas/ConnectionCountInterval'
    Connection:
      title: Connection
      required:
        - location
        - person
      type: object
      properties:
        location:
          $ref: '#/components/schemas/Location'
        person:
          $ref: '#/components/schemas/Person'
    ConnectionCountInterval:
      title: ConnectionCountInterval
      required:
        - count
        - start
        - duration
      type: object
      properties:
        count:
          title: Count
          type: integer
        start:
          title: Start
          type: string
          format: date-time
        duration:
          title: Duration
          type: number
          format: time-delta
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Location:
      title: Location
      required:
        - id
        - person_id
        - coordinates
        - creation_time
      type: object
      properties:
        id:
          title: Id
          type: integer
        person_id:
          title: Person Id
          type: integer
        coordinates:
          title: Coordinates
          maxItems: 2
          minItems: 2
          type: array
          items:
            type: number
        creation_time:
          title: Creation Time
          type: string
          format: date-time
    Person:
      title: Person
      required:
        - id
        - first_name
        - last_name
        - company_name
      type: object
      properties:
        id:
          title: Id
          type: integer
        first_name:
          title: First Name
          type: string
        last_name:
          title: Last Name
          type: string
        company_name:
          title: Company Name
          type: string
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
